#!/bin/bash
git diff

git status
echo your token is
echo 8d83a913424847dc71bb13e7256cb178564410e3 
echo press y to execute
 read keyboard
 vyes="y"
 echo your inpunt is $keyboard
if [ "$keyboard" = "$vyes" ];then
git add .
git commit
else
 echo nothing happend
fi



