#!/bin/bash
git diff

git status
echo your token is
echo hi
echo press y to execute
 read keyboard
 vyes="y"
 echo your inpunt is $keyboard
if [ "$keyboard" = "$vyes" ];then
git add .
git commit
else
 echo nothing happend
fi



